java -server \
 -XX:+PrintCommandLineFlags \
  -XX:+DisableExplicitGC \
   -XX:+UseConcMarkSweepGC \
   -XX:CMSInitiatingOccupancyFraction=80 \
   -Dcom.sun.management.jmxremote \
   -Dcom.sun.management.jmxremote.port=9191 \
   -Dcom.sun.management.jmxremote.authenticate=false \
   -Dcom.sun.management.jmxremote.ssl=false \
   -Djava.rmi.server.hostname=zarco.novasearch.org \
   -cp target/trec-car-service-1.0-SNAPSHOT-jar-with-dependencies.jar Server /scratch/fmartins/paragraphIndex/
